# Generated by Django 3.0 on 2020-04-26 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLocation',
            fields=[
                ('requestlocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('requestlocation_latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('requestlocation_longitude', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('food', 'Food'), ('mask', 'Mask'), ('baby', 'Baby-sitting')], max_length=15)),
                ('received_help', models.BooleanField(default=False)),
                ('request_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.RequestLocation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
